/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brun
 */
public class OrdenCompra extends java.applet.Applet {

    /**
     * Initializes the applet OrdenCompra
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientName = new java.awt.TextField();
        Title = new javax.swing.JLabel();
        ClientLabel = new javax.swing.JLabel();
        PrLabel = new javax.swing.JLabel();
        FstProduct = new java.awt.TextField();
        SndProduct = new java.awt.TextField();
        TrProduct = new java.awt.TextField();
        FstCostObj = new java.awt.TextField();
        SndCostObj = new java.awt.TextField();
        TrCostObj = new java.awt.TextField();
        FstAmot = new java.awt.TextField();
        SndAmot = new java.awt.TextField();
        TrAmot = new java.awt.TextField();
        VuLabel = new javax.swing.JLabel();
        AmtLabel = new javax.swing.JLabel();
        CostLabel = new javax.swing.JLabel();
        CostLabelAll = new javax.swing.JLabel();
        Calculate = new javax.swing.JButton();
        FinalText = new javax.swing.JLabel();
        FstCost = new java.awt.TextField();
        SndCost = new java.awt.TextField();
        TrCost = new java.awt.TextField();
        TotalCost = new java.awt.TextField();

        Title.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Title.setForeground(new java.awt.Color(44, 44, 44));
        Title.setText("ORDEN DE COMPRA");

        ClientLabel.setFont(new java.awt.Font("Ubuntu Condensed", 1, 14)); // NOI18N
        ClientLabel.setForeground(new java.awt.Color(44, 44, 44));
        ClientLabel.setText("CLIENTE :");
        ClientLabel.setToolTipText("");

        PrLabel.setFont(new java.awt.Font("Ubuntu Condensed", 1, 15)); // NOI18N
        PrLabel.setForeground(new java.awt.Color(44, 44, 44));
        PrLabel.setText("Producto");

        VuLabel.setFont(new java.awt.Font("Ubuntu Condensed", 1, 15)); // NOI18N
        VuLabel.setForeground(new java.awt.Color(44, 44, 44));
        VuLabel.setText("Vlr.Unitario");

        AmtLabel.setFont(new java.awt.Font("Ubuntu Condensed", 1, 15)); // NOI18N
        AmtLabel.setForeground(new java.awt.Color(44, 44, 44));
        AmtLabel.setText("Cantidad");

        CostLabel.setFont(new java.awt.Font("Ubuntu Condensed", 1, 15)); // NOI18N
        CostLabel.setForeground(new java.awt.Color(44, 44, 44));
        CostLabel.setText("Total");
        CostLabel.setToolTipText("");

        CostLabelAll.setFont(new java.awt.Font("Ubuntu Condensed", 1, 15)); // NOI18N
        CostLabelAll.setForeground(new java.awt.Color(44, 44, 44));
        CostLabelAll.setText("Valor Total");

        Calculate.setText("Calcular");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        FinalText.setForeground(new java.awt.Color(44, 44, 44));

        SndCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SndCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FinalText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SndProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FstProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TrProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(PrLabel)))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SndCostObj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FstCostObj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TrCostObj, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(VuLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CostLabelAll)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TrAmot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SndAmot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(FstAmot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AmtLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(CostLabel))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(SndCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(FstCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TrCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(Title)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClientLabel)
                                .addGap(2, 2, 2)
                                .addComponent(ClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClientLabel)
                    .addComponent(ClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PrLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VuLabel)
                        .addComponent(AmtLabel)
                        .addComponent(CostLabel)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FstProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FstCostObj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FstAmot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FstCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SndAmot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SndProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SndCostObj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TrProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TrCostObj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TrAmot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(CostLabelAll))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TrCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Calculate)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FinalText, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SndCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        // TODO add your handling code here:
        int vlr1,vlr2,vlr3;
        int Cant1,Cant2,Cant3;     
        int VlrTol1,VlrTol2,VlrTol3;
        int ValorTotal = 0;

        vlr1 = Integer.parseInt(FstCostObj.getText());
        vlr2 = Integer.parseInt(SndCostObj.getText());
        vlr3 = Integer.parseInt(TrCostObj.getText());
        Cant1 = Integer.parseInt(FstAmot.getText());
        Cant2 = Integer.parseInt(SndAmot.getText());
        Cant3 = Integer.parseInt(TrAmot.getText());
        VlrTol1 = vlr1*Cant1;
        VlrTol2 = vlr2*Cant2;
        VlrTol3 = vlr3*Cant3;
        ValorTotal = VlrTol1+VlrTol2+VlrTol3;
        FstCost.setText(""+VlrTol1);
        SndCost.setText(""+VlrTol2);
        TrCost.setText(""+VlrTol3); 
        FinalText.setText("Señor(a): "+ClientName.getText()+" el total de su compra es: "+ ValorTotal);
        TotalCost.setText(""+ValorTotal);
    }//GEN-LAST:event_CalculateActionPerformed

    private void SndCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SndCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SndCostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmtLabel;
    private javax.swing.JButton Calculate;
    private javax.swing.JLabel ClientLabel;
    private java.awt.TextField ClientName;
    private javax.swing.JLabel CostLabel;
    private javax.swing.JLabel CostLabelAll;
    private javax.swing.JLabel FinalText;
    private java.awt.TextField FstAmot;
    private java.awt.TextField FstCost;
    private java.awt.TextField FstCostObj;
    private java.awt.TextField FstProduct;
    private javax.swing.JLabel PrLabel;
    private java.awt.TextField SndAmot;
    private java.awt.TextField SndCost;
    private java.awt.TextField SndCostObj;
    private java.awt.TextField SndProduct;
    private javax.swing.JLabel Title;
    private java.awt.TextField TotalCost;
    private java.awt.TextField TrAmot;
    private java.awt.TextField TrCost;
    private java.awt.TextField TrCostObj;
    private java.awt.TextField TrProduct;
    private javax.swing.JLabel VuLabel;
    // End of variables declaration//GEN-END:variables
}
